from jsonld import JsonLdEngine
from jsonld import JsonLdPackage
from activitystreams import models, properties
from activitystreams.models import ACTIVITYSTREAMS_NS

pkg_classes = (
    models.Object,
    models.Link,
    models.Activity,
    models.IntransitiveActivity,
    models.Collection,
    models.OrderedCollection,
    models.CollectionPage,
    models.OrderedCollectionPage,
    models.Accept,
    models.TentativeAccept,
    models.Add,
    models.Arrive,
    models.Create,
    models.Delete,
    models.Follow,
    models.Ignore,
    models.Join,
    models.Leave,
    models.Like,
    models.Offer,
    models.Invite,
    models.Reject,
    models.TentativeReject,
    models.Remove,
    models.Undo,
    models.Update,
    models.View,
    models.Listen,
    models.Read,
    models.Move,
    models.Travel,
    models.Announce,
    models.Block,
    models.Flag,
    models.Dislike,
    models.Question,
    models.Application,
    models.Group,
    models.Organization,
    models.Person,
    models.Service,
    models.Relationship,
    models.Article,
    models.Document,
    models.Audio,
    models.Image,
    models.Video,
    models.Note,
    models.Page,
    models.Event,
    models.Place,
    models.Profile,
    models.Tombstone,
    models.Mention
)

pkg_properties = (
    properties.Id,
    properties.Type,
    properties.Attachment,
    properties.AttributedTo,
    properties.Actor,
    properties.Audience,
    properties.Bcc,
    properties.Bto,
    properties.Cc,
    properties.Context,
    properties.Current,
    properties.First,
    properties.Generator,
    properties.Icon,
    properties.Image,
    properties.InReplyTo,
    properties.Instrument,
    properties.Last,
    properties.Location,
    properties.Items,
    properties.OrderedItems,
    properties.UnorderedItems,
    properties.OneOf,
    properties.AnyOf,
    properties.Closed,
    properties.Origin,
    properties.Next,
    properties.Object,
    properties.Prev,
    properties.Preview,
    properties.Result,
    properties.Replies,
    properties.Tag,
    properties.Target,
    properties.To,
    properties.Url,
    properties.Accuracy,
    properties.Altitude,
    properties.Content,
    properties.Name,
    properties.Duration,
    properties.Height,
    properties.Href,
    properties.HrefLang,
    properties.PartOf,
    properties.Latitude,
    properties.Longitude,
    properties.MediaType,
    properties.EndTime,
    properties.Published,
    properties.StartTime,
    properties.Radius,
    properties.Rel,
    properties.StartIndex,
    properties.Summary,
    properties.TotalItems,
    properties.Units,
    properties.Updated,
    properties.Width,
    properties.Subject,
    properties.Relationship,
    properties.Describes,
    properties.FormerType,
    properties.Deleted
)

property_mapping = {
    models.Object.__get_namespace__(): (properties.Attachment.__get_namespace__(),
                                        properties.AttributedTo.__get_namespace__(),
                                        properties.Audience.__get_namespace__(),
                                        properties.Content.__get_namespace__(),
                                        properties.Name.__get_namespace__(),
                                        properties.EndTime.__get_namespace__(),
                                        properties.Generator.__get_namespace__(),
                                        properties.Icon.__get_namespace__(),
                                        properties.Image.__get_namespace__(),
                                        properties.InReplyTo.__get_namespace__(),
                                        properties.Location.__get_namespace__(),
                                        properties.Preview.__get_namespace__(),
                                        properties.Published.__get_namespace__(),
                                        properties.Replies.__get_namespace__(),
                                        properties.StartTime.__get_namespace__(),
                                        properties.Summary.__get_namespace__(),
                                        properties.Tag.__get_namespace__(),
                                        properties.Updated.__get_namespace__(),
                                        properties.Url.__get_namespace__(),
                                        properties.To.__get_namespace__(),
                                        properties.Bto.__get_namespace__(),
                                        properties.Cc.__get_namespace__(),
                                        properties.Bcc.__get_namespace__(),
                                        properties.MediaType.__get_namespace__(),
                                        properties.Duration.__get_namespace__(),),
    models.Link.__get_namespace__(): (properties.Href.__get_namespace__(),
                                      properties.Rel.__get_namespace__(),
                                      properties.MediaType.__get_namespace__(),
                                      properties.Name.__get_namespace__(),
                                      properties.HrefLang.__get_namespace__(),
                                      properties.Height.__get_namespace__(),
                                      properties.Width.__get_namespace__(),
                                      properties.Preview.__get_namespace__(),),
    models.Activity.__get_namespace__(): (properties.Actor.__get_namespace__(),
                                          properties.Object.__get_namespace__(),
                                          properties.Target.__get_namespace__(),
                                          properties.Result.__get_namespace__(),
                                          properties.Origin.__get_namespace__(),
                                          properties.Instrument.__get_namespace__(),),
    models.Collection.__get_namespace__(): (properties.TotalItems.__get_namespace__(),
                                            properties.Current.__get_namespace__(),
                                            properties.First.__get_namespace__(),
                                            properties.Last.__get_namespace__(),
                                            properties.Items.__get_namespace__(),
                                            properties.OrderedItems.__get_namespace__(),
                                            properties.UnorderedItems.__get_namespace__(),),
    models.CollectionPage.__get_namespace__(): (properties.PartOf.__get_namespace__(),
                                                properties.Next.__get_namespace__(),
                                                properties.Prev.__get_namespace__(),),
    models.OrderedCollectionPage.__get_namespace__(): (properties.StartIndex.__get_namespace__(),),
    models.Question.__get_namespace__(): (properties.OneOf.__get_namespace__(),
                                          properties.AnyOf.__get_namespace__(),
                                          properties.Closed.__get_namespace__(),),
    models.Relationship.__get_namespace__(): (properties.Subject.__get_namespace__(),
                                              properties.Object.__get_namespace__(),
                                              properties.Relationship.__get_namespace__(),),
    models.Place.__get_namespace__(): (properties.Accuracy.__get_namespace__(),
                                       properties.Altitude.__get_namespace__(),
                                       properties.Latitude.__get_namespace__(),
                                       properties.Longitude.__get_namespace__(),
                                       properties.Radius.__get_namespace__(),
                                       properties.Units.__get_namespace__(),),
    models.Profile.__get_namespace__(): (properties.Describes.__get_namespace__(),),
    models.Tombstone.__get_namespace__(): (properties.FormerType.__get_namespace__(),
                                           properties.Deleted.__get_namespace__(),)
}

def create_package():
    """
    Creates the ActivityStreams 2.0 package
    :return:
    """
    return JsonLdPackage(
        namespace=ACTIVITYSTREAMS_NS,
        objects=pkg_classes,
        properties=pkg_properties,
        property_mapping=property_mapping
    )

def create_engine():
    """
    Creates an engine capable of handling ActivityStreams 2.0 data
    :return:
    """
    return JsonLdEngine(create_package())
