from activitypy.jsonld.engine.jsonld_engine import JsonLdEngine
from activitypy.jsonld.package import JsonLdPackage
from activitypy.activitystreams import models, properties
from activitypy.activitystreams.models import ACTIVITYSTREAMS_NS

pkg_classes = (
    models.Object,
    models.Link,
    models.Activity,
    models.IntransitiveActivity,
    models.Collection,
    models.OrderedCollection,
    models.CollectionPage,
    models.OrderedCollectionPage,
    models.Accept,
    models.TentativeAccept,
    models.Add,
    models.Arrive,
    models.Create,
    models.Delete,
    models.Follow,
    models.Ignore,
    models.Join,
    models.Leave,
    models.Like,
    models.Offer,
    models.Invite,
    models.Reject,
    models.TentativeReject,
    models.Remove,
    models.Undo,
    models.Update,
    models.View,
    models.Listen,
    models.Read,
    models.Move,
    models.Travel,
    models.Announce,
    models.Block,
    models.Flag,
    models.Dislike,
    models.Question,
    models.Application,
    models.Group,
    models.Organization,
    models.Person,
    models.Service,
    models.Relationship,
    models.Article,
    models.Document,
    models.Audio,
    models.Image,
    models.Video,
    models.Note,
    models.Page,
    models.Event,
    models.Place,
    models.Profile,
    models.Tombstone,
    models.Mention
)

pkg_properties = (
    properties.Id,
    properties.Type,
    properties.Attachment,
    properties.AttributedTo,
    properties.Actor,
    properties.Audience,
    properties.Bcc,
    properties.Bto,
    properties.Cc,
    properties.Context,
    properties.Current,
    properties.First,
    properties.Generator,
    properties.Icon,
    properties.Image,
    properties.InReplyTo,
    properties.Instrument,
    properties.Last,
    properties.Location,
    properties.Items,
    properties.OrderedItems,
    properties.UnorderedItems,
    properties.OneOf,
    properties.AnyOf,
    properties.Closed,
    properties.Origin,
    properties.Next,
    properties.Object,
    properties.Prev,
    properties.Preview,
    properties.Result,
    properties.Replies,
    properties.Tag,
    properties.Target,
    properties.To,
    properties.Url,
    properties.Accuracy,
    properties.Altitude,
    properties.Content,
    properties.Name,
    properties.Duration,
    properties.Height,
    properties.Href,
    properties.HrefLang,
    properties.PartOf,
    properties.Latitude,
    properties.Longitude,
    properties.MediaType,
    properties.EndTime,
    properties.Published,
    properties.StartTime,
    properties.Radius,
    properties.Rel,
    properties.StartIndex,
    properties.Summary,
    properties.TotalItems,
    properties.Units,
    properties.Updated,
    properties.Width,
    properties.Subject,
    properties.Relationship,
    properties.Describes,
    properties.FormerType,
    properties.Deleted
)

property_mapping = {
    models.Object.__get_namespace__(): (properties.Attachment,
                                        properties.AttributedTo,
                                        properties.Audience,
                                        properties.Content,
                                        properties.Name,
                                        properties.EndTime,
                                        properties.Generator,
                                        properties.Icon,
                                        properties.Image,
                                        properties.InReplyTo,
                                        properties.Location,
                                        properties.Preview,
                                        properties.Published,
                                        properties.Replies,
                                        properties.StartTime,
                                        properties.Summary,
                                        properties.Tag,
                                        properties.Updated,
                                        properties.Url,
                                        properties.To,
                                        properties.Bto,
                                        properties.Cc,
                                        properties.Bcc,
                                        properties.MediaType,
                                        properties.Duration,),
    models.Link.__get_namespace__(): (properties.Href,
                                      properties.Rel,
                                      properties.MediaType,
                                      properties.Name,
                                      properties.HrefLang,
                                      properties.Height,
                                      properties.Width,
                                      properties.Preview,),
    models.Activity.__get_namespace__(): (properties.Actor,
                                          properties.Object,
                                          properties.Target,
                                          properties.Result,
                                          properties.Origin,
                                          properties.Instrument,),
    models.Collection.__get_namespace__(): (properties.TotalItems,
                                            properties.Current,
                                            properties.First,
                                            properties.Last,
                                            properties.Items,),
    models.CollectionPage.__get_namespace__(): (properties.PartOf,
                                                properties.Next,
                                                properties.Prev,),
    models.OrderedCollectionPage.__get_namespace__(): (properties.StartIndex,),
    models.Question.__get_namespace__(): (properties.OneOf,
                                          properties.AnyOf,
                                          properties.Closed,),
    models.Relationship.__get_namespace__(): (properties.Subject,
                                              properties.Object,
                                              properties.Relationship,),
    models.Place.__get_namespace__(): (properties.Accuracy,
                                       properties.Altitude,
                                       properties.Latitude,
                                       properties.Longitude,
                                       properties.Radius,
                                       properties.Units,),
    models.Profile.__get_namespace__(): (properties.Describes,),
    models.Tombstone.__get_namespace__(): (properties.FormerType,
                                           properties.Deleted,)
}

def create_package():
    """
    Creates the ActivityStreams 2.0 package
    :return:
    """
    return JsonLdPackage(
        namespace=ACTIVITYSTREAMS_NS,
        classes=pkg_classes,
        properties=pkg_properties,
        property_mapping=property_mapping
    )

def create_engine():
    """
    Creates an engine capable of handling ActivityStreams 2.0 data
    :return:
    """
    return JsonLdEngine(create_package())
